version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:8.18.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    mem_limit: 1g
    cpus: 0.5
  logstash:
    image: logstash:8.18.0
    container_name: logstash
    ports:
      - "5044:5044"  # для Filebeat 
      - "5000:5000"  # TCP input
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    mem_limit: 1g
    cpus: 0.5
  kibana:
    image: kibana:8.18.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    mem_limit: 1g
    cpus: 0.5
volumes:
  esdata:
    driver: local